name: "Generate Tag"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag Version x.x.x"
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/v${{ github.event.inputs.version }}',
                sha: context.sha
            })
